#spring.application.name=demo2

#Kiem tra dung luong neu > 10 MB thi su ly bo ra luon chua can dong if trong code ProductController su ly max file anh
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true #Mac dinh mui gio la +0
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Quandinh2111
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

api:
  prefix: api/v1